
import express, { Response, Request } from "express";
import { supabaseAdmin } from "../lib/supabase.js";
import { authenticateUser, AuthRequest } from "../middleware/auth.js";

const router = express.Router();

// Get share for a specific lesson (Authenticated User)
router.get("/:lessonId", authenticateUser, async (req: AuthRequest, res: Response) => {
    if (!req.user) return res.status(401).json({ error: "Unauthorized" });
    
    const { lessonId } = req.params;

    const { data, error } = await supabaseAdmin
        .from('course_shares')
        .select('*')
        .eq('user_id', req.user.id)
        .eq('lesson_id', lessonId)
        .single();

    if (error && error.code !== 'PGRST116') { // PGRST116 is "No rows found"
        return res.status(500).json({ error: error.message });
    }

    return res.json(data || null);
});

// Create/Update share (Authenticated User - from App)
router.post("/", authenticateUser, async (req: AuthRequest, res: Response) => {
    if (!req.user) return res.status(401).json({ error: "Unauthorized" });
    
    const { lessonId, content, aiInsight } = req.body;

    if (!lessonId) return res.status(400).json({ error: "Missing lessonId" });

    const { data, error } = await supabaseAdmin
        .from('course_shares')
        .upsert({
            user_id: req.user.id,
            lesson_id: lessonId,
            share_content: content,
            ai_insight: aiInsight, // Optional, might be generated by n8n later or client-side mock
            source: 'app',
            updated_at: new Date().toISOString()
        })
        .select()
        .single();

    if (error) return res.status(500).json({ error: error.message });
    return res.json(data);
});

// Sync endpoint for n8n (System/Admin Access)
// Expects header 'x-sync-secret' (Set this in your .env)
router.post("/sync/n8n", async (req: Request, res: Response) => {
    const secret = req.headers['x-sync-secret'];
    const envSecret = process.env.SYNC_SECRET || 'morning_n8n_secret'; // Default for dev

    if (secret !== envSecret) {
        return res.status(403).json({ error: "Forbidden: Invalid Secret" });
    }

    const { userId, lessonId, shareContent, aiInsight } = req.body;

    if (!userId || !lessonId) {
        return res.status(400).json({ error: "Missing userId or lessonId" });
    }

    const { data, error } = await supabaseAdmin
        .from('course_shares')
        .upsert({
            user_id: userId,
            lesson_id: lessonId,
            share_content: shareContent,
            ai_insight: aiInsight,
            source: 'n8n',
            updated_at: new Date().toISOString()
        })
        .select()
        .single();

    if (error) return res.status(500).json({ error: error.message });
    return res.json({ success: true, data });
});

export default router;
